package com.powerofwear.dto.payment;

import lombok.Builder;
import lombok.Data;

/**
 * DTO returned to the client after initiating a payment session with the gateway.
 * The client uses this information (e.g., redirect URL, client secret) to complete the transaction.
 */
@Data
@Builder
public class PaymentInitiationResponseDto {
    /** The unique reference ID generated by the payment gateway (e.g., Stripe Session ID). */
    private String gatewayReference;

    /** The total amount requested for payment. */
    private Double amount;

    /**
     * A secret key or token required by the client-side library (e.g., Stripe PaymentIntent client_secret).
     * This allows the client to authorize the transaction securely.
     */
    private String clientSecret;

    /**
     * Optional: A URL the customer should be redirected to if the payment flow requires it
     * (e.g., for PayPal or 3D Secure verification).
     */
    private String redirectUrl;

    /** The internal ID of the Payment entity created in your database. */
    private Long paymentId;
}